[tool.poetry]
name = "NetEase-MusicBox"
packages = [
    { include = "NEMbox" },
]
version = "0.3.0"
repository = "https://github.com/darknessomi/musicbox"
description = "A sexy command line interface musicbox"
license = "MIT"
readme = "README.md"
authors = [
    "omi <4399.omi@gmail.com>",
    "Weiliang Li <to.be.impressive@gmail.com>"
]
maintainers = [
    "omi <4399.omi@gmail.com>",
    "Weiliang Li <to.be.impressive@gmail.com>"
]
keywords = ["music", "netease", "cli", "player"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Natural Language :: Chinese (Simplified)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Multimedia :: Sound/Audio",
]


[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.24.0"
requests-cache = "^0.5.2"
fuzzywuzzy = "^0.18.0"
pycryptodomex = "^3.9.8"
python-Levenshtein = "^0.12.0"
toml = "^0.10.1"

[tool.poetry.dev-dependencies]
mypy = "^0.782"
flake8 = "^3.8.4"
black = "^20.8b1"
pytest = "^6.1.1"

[tool.poetry.scripts]
musicbox = "NEMbox.__main__:start"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
